### ISSUE TITLE
EdIE-BERT and error analysis code

### ISSUE THREAD

**Issue by jcklie** [Edinburgh-LTG/edieviz#2]
Thank you very much for this nice paper and extremely well structured and organized repo. I am very interested in the error analysis part you did with the nearest neighbour LM, is the code of this and the EdIE-BERT also in this repo or will it be added soon?

**Comment by bea-alex** [comment]
Hi Jan-Christophe,

Andreas Grivas (the first author on the paper) asked me to send you the following reply as he didn’t receive your message.

"Thank you for your kind comments! The nearest neighbour LM code is not currently in the repo, I plan to add it but I need to adapt the code as it currently relies on the ESS dataset which is not publicly available."

We are actually using the methods as part of a couple of ongoing MSc projects, so we may release the code as part of a publication later if those lead to interesting results.

**Comment by andreasgrv** [comment]
Hi Jan-Christophe,

I have updated the code to include [KNN](https://github.com/Edinburgh-LTG/edieviz/tree/master/paper/knn).
I included a simple script to run it on the NCBI disease dataset, this is of course very different from ESS, but should hopefully illustrate how to apply the approach to a NER dataset. Let me know if you have any questions.
